backend:
  name: github
  repo: kristelfung/kristelfung-com
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: home
    label: Home
    folder: src/content/home
    fields:
    slug: home
      - { name: title, label: Title }
      - { name: subtitle, label: Subtitle }
  - name: about
    label: About
    folder: src/content/about
    fields:
    slug: about
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: blog
    label: Blog
    folder: src/content/blog
    slug: blog
    fields:
      - { name: title, label: Title }
  - name: post
    label: Post
    folder: src/content/blog/posts
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }